<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-10T23:51:57 IST" name="LoginSuite" finished-at="2024-09-10T23:52:14 IST" duration-ms="16986">
    <groups>
    </groups>
    <test started-at="2024-09-10T23:51:57 IST" name="LoginTest" finished-at="2024-09-10T23:52:14 IST" duration-ms="16986">
      <class name="com.Login.TC_03_LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.Login.TC_03_LoginTest@5aa9e4eb]" started-at="2024-09-10T23:52:10 IST" name="setup" finished-at="2024-09-10T23:52:13 IST" duration-ms="2757" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="forEmptyUnsuccessfulLogintest()[pri:0, instance:com.Login.TC_03_LoginTest@5aa9e4eb]" started-at="2024-09-10T23:52:13 IST" name="forEmptyUnsuccessfulLogintest" finished-at="2024-09-10T23:52:14 IST" duration-ms="594" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Email: This field is required.
Password: This field is required expected [empty credentials] but found [Email: This field is required.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Email: This field is required.
Password: This field is required expected [empty credentials] but found [Email: This field is required.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.Login.TC_03_LoginTest.forEmptyUnsuccessfulLogintest(TC_03_LoginTest.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forEmptyUnsuccessfulLogintest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.Login.TC_03_LoginTest@5aa9e4eb]" started-at="2024-09-10T23:52:14 IST" name="tearDown" finished-at="2024-09-10T23:52:14 IST" duration-ms="210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Login.TC_03_LoginTest -->
      <class name="com.Login.TC_02_LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.Login.TC_02_LoginTest@3fc2959f]" started-at="2024-09-10T23:52:06 IST" name="setup" finished-at="2024-09-10T23:52:08 IST" duration-ms="2628" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="UnsuccessfulLogintest()[pri:0, instance:com.Login.TC_02_LoginTest@3fc2959f]" started-at="2024-09-10T23:52:08 IST" name="UnsuccessfulLogintest" finished-at="2024-09-10T23:52:10 IST" duration-ms="1671" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Please enter a correct username and password. Note that both fields may be case-sensitive. expected [Invalid credentials] but found [Please enter a correct username and password. Note that both fields may be case-sensitive.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Please enter a correct username and password. Note that both fields may be case-sensitive. expected [Invalid credentials] but found [Please enter a correct username and password. Note that both fields may be case-sensitive.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.Login.TC_02_LoginTest.UnsuccessfulLogintest(TC_02_LoginTest.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UnsuccessfulLogintest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.Login.TC_02_LoginTest@3fc2959f]" started-at="2024-09-10T23:52:10 IST" name="tearDown" finished-at="2024-09-10T23:52:10 IST" duration-ms="339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Login.TC_02_LoginTest -->
      <class name="com.Login.TC_01_LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.Login.TC_01_LoginTest@1573f9fc]" started-at="2024-09-10T23:51:57 IST" name="setup" finished-at="2024-09-10T23:52:03 IST" duration-ms="6363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="SuccessfulLogintest()[pri:0, instance:com.Login.TC_01_LoginTest@1573f9fc]" started-at="2024-09-10T23:52:03 IST" name="SuccessfulLogintest" finished-at="2024-09-10T23:52:06 IST" duration-ms="2096" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SuccessfulLogintest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.Login.TC_01_LoginTest@1573f9fc]" started-at="2024-09-10T23:52:06 IST" name="tearDown" finished-at="2024-09-10T23:52:06 IST" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Login.TC_01_LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- LoginSuite -->
</testng-results>
